server:
  port: 9999
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  application:
    name: springcloud-server-api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    api-image:
      path: /image/**
      serviceId: base-service-image
    api-sso:
      path: /sso/**
      serviceId: sso-server
    api-crm:
      path: /crm/**
      serviceId: crm-server
    api-a:
      path: /api-a/**
      serviceId:  springcloud-consumer-ribbon
    api-b:
      path: /api-b/**
      serviceId:  springcloud-consumer-feign
    api-c:
      path: /api-c/**
      serviceId: springcloud-producer-rest
    api-d:
      path: /api-d/**
      serviceId: springcloud-server-bus-rabbitmq

