server:
  port: 8887

spring:
  application:
    name: springcloud-producer-config-rest # 服务名称
  cloud:
    config:
      name: springcloud-service-config
      profile: dev
      uri: http://127.0.0.1:8888
      #discovery:
        #enabled: true
        #serviceId: springcloud-server-config
  rabbitmq:
    host: 192.168.22.145
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8080/eureka/  # 服务注册地址
  instance:
      lease-renewal-interval-in-seconds: 45 # 用于定义服务续约任务的调用间隔时间，默认30秒
      lease-expiration-duration-in-seconds: 90  # 用于定义服务失效的时间 ，默认90秒

management:
  security:
    enabled: false
endpoints:
  refresh:
    enabled: true


