server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false # 由于很容易出发eureka server自我保护机制，使得注册中心的服务不能够正常下线，关闭自我保护机制，以确保注册中心可以将不可用的服务正确剔除
  client:
    registerWithEureka: false #由于该应用为注册中心，所以设置为false，代表不像注册中心注册自己
    fetchRegistry: false # 由于注册中心的作用就是维护服务实例，他并不需要去检索服务，所以设置为false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: springcloud-eureka-server



