server:
  port: 8888
management:
  security:
    enabled: false
spring:
  application:
    name: springcloud-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuhaibao324/08demo.springcloud
          search-paths: springcloud-repo-config
          username:
          password:
          force-pull: true
      label: master
  rabbitmq:
    host: 192.168.22.145
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/